=== RickLugtigheid/Node-Ui/lib/styleSchema.json
{    
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/root.json",
    "type": "object",
    "properties": {
        "window":{
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string",
                    "default": "./path/icon.ico"
                },
                "bg-color": {
                    "$ref": "#/definitions/color"
                }
            }
        },
        "button":{
            "$ref": "#/definitions/element"
        },
        "button-active":{
            "$ref": "#/definitions/element"
        },
        "button-hover":{
            "$ref": "#/definitions/element"
        },

        "label":{
            "$ref": "#/definitions/element"
        },
        "label-hover":{
            "$ref": "#/definitions/element"
        },
        
        "checkbox":{
            "$ref": "#/definitions/element"
        },
        "checkbox-active":{
            "$ref": "#/definitions/element"
        },

        "textbox":{
            "$ref": "#/definitions/element"
        },
        "textbox-active":{
            "$ref": "#/definitions/element"
        }
    },
    "definitions":{
        "element":{
            "type": "object",
            "properties": {
                "bg-color": {
                    "$ref": "#/definitions/color"
                },
                "font": {
                    "type": "object",
                    "properties": {
                        "font-color": {
                            "$ref": "#/definitions/color"
                        },
                        "font-size": {
                            "type":"number"
                        }, 
                        "font-style": {
                            "type":"string",
                            "default": "none",
                            "examples": [
                                "bold",
                                "italic",
                                "bold italic"
                            ]
                        },
                        "font": {
                            "type":"string",
                            "default": "Arial",
                            "examples": [
                                "System", 
                                "Terminal", 
                                "Fixedsys", 
                                "Modern", 
                                "Roman", 
                                "Script", 
                                "Courier", 
                                "MS Serif", 
                                "MS Sans Serif", 
                                "Small Fonts", 
                                "Source Sans Pro Black", 
                                "Opus Chords Std",
                                "Marlett", 
                                "Arabic Transparent", 
                                "Arial Black", 
                                "Bahnschrift Light", 
                                "Bahnschrift SemiLight", 
                                "Bahnschrift", 
                                "Bahnschrift SemiBold",   
                                "Calibri", 
                                "Calibri Light", 
                                "Cambria", 
                                "Cambria Math", 
                                "Candara",
                                "Candara Light", 
                                "Comic Sans MS", 
                                "Consolas", "Constantia", 
                                "Corbel", 
                                "Corbel Light", 
                                "Courier New", 
                                "MS Gothic", 
                                "Myanmar Text", 
                                "Symbol", 
                                "Tahoma", 
                                "Times New Roman", 
                                "Yu Gothic",  
                                "HoloLens MDL2 Assets", 
                                "Lato"
                            ]
                        }
                    }
                }
            }
        },
        "color": {
            "type": "string",
            "default": "#000000",
            "examples": [
                "red",
                "blue",
                "green",
                "cyan",
                "turquoise",
                "orange",
                "salmon",
                "yellow",
                "pink",
                "violet",
                "purple",
                "gold",
                "silver",
                "gray",
                "black",
                "white",
                "snow",
                "white smoke",
                "bisque",
                "azure"
            ]
        }
    }
}

=== RickLugtigheid/Node-Ui/style.json
{
    "window":{
        "bg-color":  "#1F1F1F"
    },
    "button":{
        "bg-color": "#242424",
        "text-color": "white"
    },
    "label":{
        "bg-color": "#1F1F1F",
        "text-color": "white"
    },
    "checkbox":{
        "bg-color": "#1F1F1F",
        "text-color": "#29FF00"
    }
}
